// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { Theme } from "theme.slint";
import { TitleLabel } from "title_label.slint";

export Card := Rectangle {
    callback clicked <=> touch-area.clicked;

    property <length> itemWidth;

    width: itemWidth;
    height: itemWidth;

    property <string> title: "title";
    property <bool> is-selected: false;
    property <image> image-source <=> image.source;
    property <length> spacing: Theme.spacing-medium;
    property <length> title-spacing: Theme.spacing-medium;
    property <length> title-area-height: Theme.size-small;

    border-radius: width / 10;
    background: Theme.background-regular;
    clip: false;

    touch-area := TouchArea {}

    image := Image {
        x: (parent.width - width) / 2;
        y: (parent.height - height) / 2;
        width: 80%;
        height: 80%;
        colorize: Theme.foreground;

        animate colorize { duration: Theme.duration-fast; }
    }

    states [
        pressed-selected when touch-area.pressed && is-selected  : {
            background: Theme.background-selected-pressed;
            image.colorize: Theme.foreground-selected-pressed;
            width: itemWidth * 1.2;
            height: itemWidth * 1.2;
        }
        hover-selected when touch-area.has-hover && is-selected  : {
            background: Theme.background-selected-hover;
            image.colorize: Theme.foreground-selected-hover;
            width: itemWidth * 1.2;
            height: itemWidth * 1.2;
        }
        pressed when touch-area.pressed : {
            background: Theme.background-pressed;
            image.colorize: Theme.foreground-pressed;
        }

        hover when touch-area.has-hover: {
            background: Theme.background-hover;
            image.colorize: Theme.foreground-hover;
        }
        selected when is-selected : {
            background: Theme.background-selected;
            image.colorize: Theme.foreground-selected;
            width: itemWidth * 1.2;
            height: itemWidth * 1.2;
        }
     ]

     animate width { duration: Theme.duration-regular; easing: ease-in; }
     animate height { duration: Theme.duration-regular; easing: ease-in; }
     animate background { duration: Theme.duration-fast; }
}